"""Initial schemas

Revision ID: d347bdebec4d
Revises: 
Create Date: 2025-04-30 10:14:31.297056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd347bdebec4d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Initial migration might create base tables if not empty
    # Or just pass if tables are created by the application/later migrations
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Explicitly drop tables managed by migrations to ensure clean state
    # Drop tables in reverse order of dependency (generally, association tables first)
    op.drop_table('data_product_tag_association')
    op.drop_table('output_ports')
    op.drop_table('input_ports')
    op.drop_table('data_product_info')
    op.drop_table('tags')
    op.drop_table('data_asset_reviews')
    op.drop_table('audit_log')
    op.drop_table('data_products') # Depends on info, input/output ports, tags
    op.drop_table('settings')
    op.drop_table('notifications')
    op.drop_table('data_domains')
    op.drop_table('app_roles')
    # ### end Alembic commands ###
