"""add_genie_spaces_table

Revision ID: 6d6f1ff0c524
Revises: 3f322c53b3c7
Create Date: 2025-12-01 15:54:40.413968

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6d6f1ff0c524'
down_revision: Union[str, None] = '3f322c53b3c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('genie_spaces',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('space_id', sa.String(), nullable=False),
    sa.Column('space_name', sa.String(), nullable=False),
    sa.Column('space_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('datasets', sa.JSON(), nullable=True),
    sa.Column('product_ids', sa.JSON(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_genie_spaces_space_id', 'genie_spaces', ['space_id'], unique=True)
    op.create_index('ix_genie_spaces_space_name', 'genie_spaces', ['space_name'], unique=False)
    op.create_index('ix_genie_spaces_status', 'genie_spaces', ['status'], unique=False)
    op.create_index('ix_genie_spaces_created_by', 'genie_spaces', ['created_by'], unique=False)
    op.create_index('ix_genie_spaces_status_created_by', 'genie_spaces', ['status', 'created_by'], unique=False)
    # Drop tables in correct order (child tables first)
    op.drop_table('data_quality_check_results')
    op.drop_table('data_contract_validation_results')
    op.drop_table('data_quality_check_runs')
    op.drop_table('data_contract_validation_runs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_quality_check_runs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('checks_passed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checks_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['data_contracts.id'], name='data_quality_check_runs_contract_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='data_quality_check_runs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('data_contract_validation_results',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('check_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('details_json', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['data_contract_validation_runs.id'], name=op.f('data_contract_validation_results_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('data_contract_validation_results_pkey'))
    )
    op.create_table('data_contract_validation_runs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('checks_passed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('checks_failed', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['contract_id'], ['data_contracts.id'], name=op.f('data_contract_validation_runs_contract_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('data_contract_validation_runs_pkey'))
    )
    op.create_table('data_quality_check_results',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('run_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('contract_id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('object_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('check_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('column_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('passed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('violations_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['data_quality_check_runs.id'], name=op.f('data_quality_check_results_run_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('data_quality_check_results_pkey'))
    )
    op.drop_index('ix_genie_spaces_status_created_by', table_name='genie_spaces')
    op.drop_index('ix_genie_spaces_created_by', table_name='genie_spaces')
    op.drop_index('ix_genie_spaces_status', table_name='genie_spaces')
    op.drop_index('ix_genie_spaces_space_name', table_name='genie_spaces')
    op.drop_index('ix_genie_spaces_space_id', table_name='genie_spaces')
    op.drop_table('genie_spaces')
    # ### end Alembic commands ###
